name: Watch for changes

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  generated-code:
    if: github.repository == 'async-aws/aws'
    name: Assert Generated Code is uptodate with last version
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Determine composer cache directory
        id: determine-composer-cache-directory
        run: echo ::set-output name=directory::$(composer config cache-dir)

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-composer-${{ github.sha }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Download dependencies
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Regenerate code against last version
        id: fetch_version
        run: |
          .github/workflows/bin/refresh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          push-to-fork: async-aws-bot/aws
          author: AsyncAws Bot <github@async-aws.com>
          committer: AsyncAws Bot <github@async-aws.com>
          commit-message: update generated code
          title: Update generated code
          body: |
            The AWS API contract changed with version ${{ steps.fetch_version.outputs.last }}.

            This PR contains the new definition for Services.
          branch: bot-code-update
